export enum BiasRating {
  LEFT = 'Left',
  LEAN_LEFT = 'Lean Left',
  CENTER = 'Center',
  LEAN_RIGHT = 'Lean Right',
  RIGHT = 'Right',
}

export interface NewsSource {
  id: string;
  name: string;
  bias: BiasRating;
  logoUrl?: string;
  domain: string;
}

export interface Article {
  id: string;
  title: string;
  summary: string;
  url: string;
  publishedAt: string;
  source: NewsSource;
  // Included from the NER pipeline
  entities: {
    people: string[];
    places: string[];
    organizations: string[];
  };
}

export interface NewsCluster {
  id: string;
  topicLabel: string; // Generated by BERTopic
  keywords: string[]; // Generated by BERTopic
  summary: string; // Generative AI summary of the cluster
  articles: Article[];
  biasDistribution: {
    left: number; // percentage 0-100
    center: number;
    right: number;
  };
  totalSources: number;
  lastUpdated: string;
}

export interface UserProfile {
  name: string;
  readingHistory: {
    left: number;
    center: number;
    right: number;
  };
}